name: null

channels:
  - pytorch
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=10.2
  - pip=20.0
  - python=3.7
  - pytorch=1.3.1
  - torchvision=0.4.2
  - pillow=6.2.1
  - tqdm=4.42.1
  - lmdb=0.9.29
