name: null

channels:
  - pytorch
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=10.2
  - pip=20.0
  - pip:
    - torch==1.3.1
    - torchvision==0.4.2
    - wandb==0.13.5
  - python=3.7
  - pillow=6.2.1
  - tqdm=4.42.1
  - python-lmdb=0.98
  - wandb
